// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migraciones/CLI siempre contra la conexión directa (DIRECT_URL) cuando existe
    // -- necesaria en Supabase porque el pooler (DATABASE_URL en modo pgbouncer)
    // no soporta el protocolo que usan migrate/db push. En dev local (un solo
    // Postgres, sin pooler) no hay DIRECT_URL y cae a DATABASE_URL, sin cambios.
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
