export interface SkillCatalogEntry {
  name: string;
  category: string;
}

export const SKILL_CATALOG: SkillCatalogEntry[] = [
  { name: 'Angular', category: 'Frontend' },
  { name: 'Angular Material', category: 'Frontend' },
  { name: 'Angular CLI', category: 'Frontend' },
  { name: 'React', category: 'Frontend' },
  { name: 'React Native', category: 'Móvil' },
  { name: 'Vue.js', category: 'Frontend' },
  { name: 'Svelte', category: 'Frontend' },
  { name: 'Next.js', category: 'Frontend' },
  { name: 'Nuxt.js', category: 'Frontend' },
  { name: 'Gatsby', category: 'Frontend' },
  { name: 'Redux', category: 'Frontend' },
  { name: 'Zustand', category: 'Frontend' },
  { name: 'NgRx', category: 'Frontend' },
  { name: 'RxJS', category: 'Frontend' },
  { name: 'jQuery', category: 'Frontend' },
  { name: 'Bootstrap', category: 'Frontend' },
  { name: 'Tailwind CSS', category: 'Frontend' },
  { name: 'Material UI', category: 'Frontend' },
  { name: 'PrimeNG', category: 'Frontend' },
  { name: 'Chakra UI', category: 'Frontend' },
  { name: 'Ant Design', category: 'Frontend' },
  { name: 'HTML5', category: 'Frontend' },
  { name: 'CSS3', category: 'Frontend' },
  { name: 'Sass', category: 'Frontend' },
  { name: 'LESS', category: 'Frontend' },
  { name: 'Styled Components', category: 'Frontend' },
  { name: 'Responsive Design', category: 'Frontend' },
  { name: 'Web Components', category: 'Frontend' },
  { name: 'PWA', category: 'Frontend' },
  { name: 'SPA', category: 'Frontend' },
  { name: 'SSR', category: 'Frontend' },
  { name: 'Webpack', category: 'Frontend' },
  { name: 'Vite', category: 'Frontend' },
  { name: 'ESBuild', category: 'Frontend' },
  { name: 'Babel', category: 'Frontend' },

  { name: 'JavaScript', category: 'Lenguajes' },
  { name: 'TypeScript', category: 'Lenguajes' },
  { name: 'Python', category: 'Lenguajes' },
  { name: 'Java', category: 'Lenguajes' },
  { name: 'C#', category: 'Lenguajes' },
  { name: 'C++', category: 'Lenguajes' },
  { name: 'C', category: 'Lenguajes' },
  { name: 'Go', category: 'Lenguajes' },
  { name: 'Rust', category: 'Lenguajes' },
  { name: 'PHP', category: 'Lenguajes' },
  { name: 'Ruby', category: 'Lenguajes' },
  { name: 'Kotlin', category: 'Lenguajes' },
  { name: 'Swift', category: 'Lenguajes' },
  { name: 'Dart', category: 'Lenguajes' },
  { name: 'Scala', category: 'Lenguajes' },
  { name: 'R', category: 'Lenguajes' },
  { name: 'MATLAB', category: 'Lenguajes' },
  { name: 'SQL', category: 'Lenguajes' },
  { name: 'PL/SQL', category: 'Lenguajes' },
  { name: 'Bash', category: 'Lenguajes' },
  { name: 'PowerShell', category: 'Lenguajes' },
  { name: 'Perl', category: 'Lenguajes' },
  { name: 'Lua', category: 'Lenguajes' },
  { name: 'Elixir', category: 'Lenguajes' },
  { name: 'Haskell', category: 'Lenguajes' },
  { name: 'Clojure', category: 'Lenguajes' },
  { name: 'F#', category: 'Lenguajes' },
  { name: 'Groovy', category: 'Lenguajes' },
  { name: 'Objective-C', category: 'Lenguajes' },
  { name: 'Assembly', category: 'Lenguajes' },
  { name: 'COBOL', category: 'Lenguajes' },
  { name: 'Fortran', category: 'Lenguajes' },
  { name: 'Julia', category: 'Lenguajes' },
  { name: 'Solidity', category: 'Lenguajes' },
  { name: 'VBA', category: 'Lenguajes' },

  { name: 'NestJS', category: 'Backend' },
  { name: 'Express.js', category: 'Backend' },
  { name: 'Node.js', category: 'Backend' },
  { name: 'Spring Boot', category: 'Backend' },
  { name: 'Django', category: 'Backend' },
  { name: 'Flask', category: 'Backend' },
  { name: 'FastAPI', category: 'Backend' },
  { name: 'Laravel', category: 'Backend' },
  { name: 'ASP.NET Core', category: 'Backend' },
  { name: 'Ruby on Rails', category: 'Backend' },
  { name: 'GraphQL', category: 'Backend' },
  { name: 'REST API', category: 'Backend' },
  { name: 'WebSockets', category: 'Backend' },
  { name: 'Microservicios', category: 'Backend' },
  { name: 'API Gateway', category: 'Backend' },
  { name: 'gRPC', category: 'Backend' },
  { name: 'SOAP', category: 'Backend' },
  { name: 'Socket.IO', category: 'Backend' },
  { name: 'Kafka', category: 'Backend' },
  { name: 'RabbitMQ', category: 'Backend' },
  { name: 'Redis Pub/Sub', category: 'Backend' },
  { name: 'Bull Queue', category: 'Backend' },
  { name: 'Celery', category: 'Backend' },
  { name: 'Cron Jobs', category: 'Backend' },
  { name: 'Serverless', category: 'Backend' },
  { name: 'Lambda Functions', category: 'Backend' },
  { name: 'Middleware', category: 'Backend' },
  { name: 'CORS', category: 'Backend' },
  { name: 'Rate Limiting', category: 'Backend' },
  { name: 'Load Balancing', category: 'Backend' },
  { name: 'Caching', category: 'Backend' },
  { name: 'Session Management', category: 'Backend' },

  { name: 'PostgreSQL', category: 'Bases de Datos' },
  { name: 'MySQL', category: 'Bases de Datos' },
  { name: 'SQL Server', category: 'Bases de Datos' },
  { name: 'Oracle DB', category: 'Bases de Datos' },
  { name: 'MongoDB', category: 'Bases de Datos' },
  { name: 'Redis', category: 'Bases de Datos' },
  { name: 'Firebase', category: 'Bases de Datos' },
  { name: 'Supabase', category: 'Bases de Datos' },
  { name: 'SQLite', category: 'Bases de Datos' },
  { name: 'MariaDB', category: 'Bases de Datos' },
  { name: 'Cassandra', category: 'Bases de Datos' },
  { name: 'Elasticsearch', category: 'Bases de Datos' },
  { name: 'DynamoDB', category: 'Bases de Datos' },
  { name: 'Neo4j', category: 'Bases de Datos' },
  { name: 'Prisma', category: 'Bases de Datos' },
  { name: 'TypeORM', category: 'Bases de Datos' },
  { name: 'Sequelize', category: 'Bases de Datos' },
  { name: 'Entity Framework', category: 'Bases de Datos' },
  { name: 'Hibernate', category: 'Bases de Datos' },
  { name: 'JDBC', category: 'Bases de Datos' },
  { name: 'ODBC', category: 'Bases de Datos' },
  { name: 'Database Design', category: 'Bases de Datos' },
  { name: 'Normalization', category: 'Bases de Datos' },
  { name: 'ERD', category: 'Bases de Datos' },
  { name: 'Stored Procedures', category: 'Bases de Datos' },
  { name: 'Triggers', category: 'Bases de Datos' },
  { name: 'Views', category: 'Bases de Datos' },
  { name: 'Indexes', category: 'Bases de Datos' },
  { name: 'Query Optimization', category: 'Bases de Datos' },
  { name: 'Backups', category: 'Bases de Datos' },
  { name: 'Replication', category: 'Bases de Datos' },
  { name: 'Sharding', category: 'Bases de Datos' },
  { name: 'ETL', category: 'Bases de Datos' },
  { name: 'Data Warehousing', category: 'Bases de Datos' },
  { name: 'Data Modeling', category: 'Bases de Datos' },
  { name: 'Migrations', category: 'Bases de Datos' },
  { name: 'Connection Pooling', category: 'Bases de Datos' },

  { name: 'Docker', category: 'DevOps' },
  { name: 'Kubernetes', category: 'DevOps' },
  { name: 'Docker Compose', category: 'DevOps' },
  { name: 'Docker Swarm', category: 'DevOps' },
  { name: 'GitHub Actions', category: 'DevOps' },
  { name: 'GitLab CI', category: 'DevOps' },
  { name: 'Jenkins', category: 'DevOps' },
  { name: 'CircleCI', category: 'DevOps' },
  { name: 'Travis CI', category: 'DevOps' },
  { name: 'Bitbucket Pipelines', category: 'DevOps' },
  { name: 'ArgoCD', category: 'DevOps' },
  { name: 'Helm', category: 'DevOps' },
  { name: 'Terraform', category: 'DevOps' },
  { name: 'Ansible', category: 'DevOps' },
  { name: 'Puppet', category: 'DevOps' },
  { name: 'Chef', category: 'DevOps' },
  { name: 'Vagrant', category: 'DevOps' },
  { name: 'Nginx', category: 'DevOps' },
  { name: 'Apache', category: 'DevOps' },
  { name: 'HAProxy', category: 'DevOps' },
  { name: 'Linux', category: 'DevOps' },
  { name: 'Ubuntu', category: 'DevOps' },
  { name: 'CentOS', category: 'DevOps' },
  { name: 'Debian', category: 'DevOps' },
  { name: 'Red Hat', category: 'DevOps' },
  { name: 'Shell Scripting', category: 'DevOps' },
  { name: 'Cron', category: 'DevOps' },
  { name: 'Systemd', category: 'DevOps' },
  { name: 'CI/CD', category: 'DevOps' },
  { name: 'Monitoring', category: 'DevOps' },
  { name: 'Prometheus', category: 'DevOps' },
  { name: 'Grafana', category: 'DevOps' },
  { name: 'Datadog', category: 'DevOps' },
  { name: 'New Relic', category: 'DevOps' },
  { name: 'ELK Stack', category: 'DevOps' },
  { name: 'Logstash', category: 'DevOps' },
  { name: 'Kibana', category: 'DevOps' },
  { name: 'Nagios', category: 'DevOps' },
  { name: 'Zabbix', category: 'DevOps' },
  { name: 'Sentry', category: 'DevOps' },
  { name: 'PM2', category: 'DevOps' },
  { name: 'Supervisor', category: 'DevOps' },
  { name: 'OpenStack', category: 'DevOps' },
  { name: 'VMware', category: 'DevOps' },
  { name: 'VirtualBox', category: 'DevOps' },

  { name: 'AWS', category: 'Cloud' },
  { name: 'Amazon S3', category: 'Cloud' },
  { name: 'Amazon EC2', category: 'Cloud' },
  { name: 'Amazon RDS', category: 'Cloud' },
  { name: 'AWS Lambda', category: 'Cloud' },
  { name: 'AWS CloudFront', category: 'Cloud' },
  { name: 'AWS Route 53', category: 'Cloud' },
  { name: 'AWS IAM', category: 'Cloud' },
  { name: 'AWS SQS', category: 'Cloud' },
  { name: 'AWS SNS', category: 'Cloud' },
  { name: 'Azure', category: 'Cloud' },
  { name: 'Azure DevOps', category: 'Cloud' },
  { name: 'Azure Functions', category: 'Cloud' },
  { name: 'Google Cloud', category: 'Cloud' },
  { name: 'Google Cloud Functions', category: 'Cloud' },
  { name: 'Google Cloud Run', category: 'Cloud' },
  { name: 'Firebase Cloud Messaging', category: 'Cloud' },
  { name: 'Heroku', category: 'Cloud' },
  { name: 'Netlify', category: 'Cloud' },
  { name: 'Vercel', category: 'Cloud' },
  { name: 'DigitalOcean', category: 'Cloud' },
  { name: 'Linode', category: 'Cloud' },
  { name: 'Cloudflare', category: 'Cloud' },
  { name: 'CDN', category: 'Cloud' },
  { name: 'Object Storage', category: 'Cloud' },
  { name: 'Block Storage', category: 'Cloud' },
  { name: 'Auto Scaling', category: 'Cloud' },
  { name: 'Infrastructure as Code', category: 'Cloud' },
  { name: 'Cloud Architecture', category: 'Cloud' },
  { name: 'Multi-cloud', category: 'Cloud' },
  { name: 'Hybrid Cloud', category: 'Cloud' },
  { name: 'Cloud Migration', category: 'Cloud' },
  { name: 'Cloud Security', category: 'Cloud' },
  { name: 'Cloud Cost Optimization', category: 'Cloud' },

  { name: 'Pandas', category: 'Datos / IA' },
  { name: 'NumPy', category: 'Datos / IA' },
  { name: 'Power BI', category: 'Datos / IA' },
  { name: 'Tableau', category: 'Datos / IA' },
  { name: 'Excel', category: 'Datos / IA' },
  { name: 'Google Sheets', category: 'Datos / IA' },
  { name: 'Looker', category: 'Datos / IA' },
  { name: 'Machine Learning', category: 'Datos / IA' },
  { name: 'Deep Learning', category: 'Datos / IA' },
  { name: 'Neural Networks', category: 'Datos / IA' },
  { name: 'Data Analysis', category: 'Datos / IA' },
  { name: 'Data Engineering', category: 'Datos / IA' },
  { name: 'Data Science', category: 'Datos / IA' },
  { name: 'Big Data', category: 'Datos / IA' },
  { name: 'Apache Spark', category: 'Datos / IA' },
  { name: 'Apache Hadoop', category: 'Datos / IA' },
  { name: 'TensorFlow', category: 'Datos / IA' },
  { name: 'PyTorch', category: 'Datos / IA' },
  { name: 'Scikit-learn', category: 'Datos / IA' },
  { name: 'Keras', category: 'Datos / IA' },
  { name: 'NLP', category: 'Datos / IA' },
  { name: 'Computer Vision', category: 'Datos / IA' },
  { name: 'OpenCV', category: 'Datos / IA' },
  { name: 'Reinforcement Learning', category: 'Datos / IA' },
  { name: 'Feature Engineering', category: 'Datos / IA' },
  { name: 'Model Deployment', category: 'Datos / IA' },
  { name: 'MLOps', category: 'Datos / IA' },
  { name: 'Statistics', category: 'Datos / IA' },
  { name: 'Regression', category: 'Datos / IA' },
  { name: 'Classification', category: 'Datos / IA' },
  { name: 'Clustering', category: 'Datos / IA' },
  { name: 'Time Series', category: 'Datos / IA' },
  { name: 'A/B Testing', category: 'Datos / IA' },
  { name: 'Data Visualization', category: 'Datos / IA' },
  { name: 'Matplotlib', category: 'Datos / IA' },
  { name: 'Seaborn', category: 'Datos / IA' },
  { name: 'Plotly', category: 'Datos / IA' },
  { name: 'D3.js', category: 'Datos / IA' },
  { name: 'Jupyter', category: 'Datos / IA' },
  { name: 'Anaconda', category: 'Datos / IA' },
  { name: 'Apache Airflow', category: 'Datos / IA' },
  { name: 'Snowflake', category: 'Datos / IA' },
  { name: 'Databricks', category: 'Datos / IA' },

  { name: 'Jest', category: 'QA / Testing' },
  { name: 'Cypress', category: 'QA / Testing' },
  { name: 'Playwright', category: 'QA / Testing' },
  { name: 'Selenium', category: 'QA / Testing' },
  { name: 'Mocha', category: 'QA / Testing' },
  { name: 'Chai', category: 'QA / Testing' },
  { name: 'Jasmine', category: 'QA / Testing' },
  { name: 'Karma', category: 'QA / Testing' },
  { name: 'Pytest', category: 'QA / Testing' },
  { name: 'JUnit', category: 'QA / Testing' },
  { name: 'TestNG', category: 'QA / Testing' },
  { name: 'Postman', category: 'QA / Testing' },
  { name: 'Insomnia', category: 'QA / Testing' },
  { name: 'Swagger', category: 'QA / Testing' },
  { name: 'Unit Testing', category: 'QA / Testing' },
  { name: 'Integration Testing', category: 'QA / Testing' },
  { name: 'E2E Testing', category: 'QA / Testing' },
  { name: 'QA Manual', category: 'QA / Testing' },
  { name: 'QA Automation', category: 'QA / Testing' },
  { name: 'Test Cases', category: 'QA / Testing' },
  { name: 'Bug Tracking', category: 'QA / Testing' },
  { name: 'Regression Testing', category: 'QA / Testing' },
  { name: 'Performance Testing', category: 'QA / Testing' },
  { name: 'JMeter', category: 'QA / Testing' },
  { name: 'Load Testing', category: 'QA / Testing' },
  { name: 'Stress Testing', category: 'QA / Testing' },
  { name: 'TDD', category: 'QA / Testing' },
  { name: 'BDD', category: 'QA / Testing' },
  { name: 'Cucumber', category: 'QA / Testing' },
  { name: 'Code Coverage', category: 'QA / Testing' },
  { name: 'SonarQube', category: 'QA / Testing' },

  { name: 'JWT', category: 'Seguridad' },
  { name: 'OAuth2', category: 'Seguridad' },
  { name: 'OpenID Connect', category: 'Seguridad' },
  { name: 'SAML', category: 'Seguridad' },
  { name: 'OWASP', category: 'Seguridad' },
  { name: 'Cybersecurity', category: 'Seguridad' },
  { name: 'Ethical Hacking', category: 'Seguridad' },
  { name: 'Penetration Testing', category: 'Seguridad' },
  { name: 'Network Security', category: 'Seguridad' },
  { name: 'Firewalls', category: 'Seguridad' },
  { name: 'VPN', category: 'Seguridad' },
  { name: 'SSL/TLS', category: 'Seguridad' },
  { name: 'HTTPS', category: 'Seguridad' },
  { name: 'Encryption', category: 'Seguridad' },
  { name: 'Hashing', category: 'Seguridad' },
  { name: 'bcrypt', category: 'Seguridad' },
  { name: 'Secure Coding', category: 'Seguridad' },
  { name: 'Authentication', category: 'Seguridad' },
  { name: 'Authorization', category: 'Seguridad' },
  { name: 'RBAC', category: 'Seguridad' },
  { name: '2FA', category: 'Seguridad' },
  { name: 'CSRF Protection', category: 'Seguridad' },
  { name: 'XSS Prevention', category: 'Seguridad' },
  { name: 'SQL Injection Prevention', category: 'Seguridad' },
  { name: 'Security Auditing', category: 'Seguridad' },
  { name: 'ISO 27001', category: 'Seguridad' },
  { name: 'GDPR', category: 'Seguridad' },
  { name: 'SOC 2', category: 'Seguridad' },
  { name: 'Vulnerability Scanning', category: 'Seguridad' },
  { name: 'SIEM', category: 'Seguridad' },

  { name: 'Flutter', category: 'Móvil' },
  { name: 'Android', category: 'Móvil' },
  { name: 'iOS', category: 'Móvil' },
  { name: 'Kotlin Android', category: 'Móvil' },
  { name: 'Swift iOS', category: 'Móvil' },
  { name: 'Ionic', category: 'Móvil' },
  { name: 'Xamarin', category: 'Móvil' },
  { name: 'Cordova', category: 'Móvil' },
  { name: 'Mobile UI', category: 'Móvil' },
  { name: 'Mobile Backend', category: 'Móvil' },
  { name: 'App Store', category: 'Móvil' },
  { name: 'Google Play', category: 'Móvil' },
  { name: 'Push Notifications', category: 'Móvil' },
  { name: 'Geolocation', category: 'Móvil' },
  { name: 'Camera API', category: 'Móvil' },
  { name: 'Bluetooth LE', category: 'Móvil' },
  { name: 'Offline Storage', category: 'Móvil' },
  { name: 'Mobile Testing', category: 'Móvil' },
  { name: 'Appium', category: 'Móvil' },
  { name: 'Detox', category: 'Móvil' },

  { name: 'Figma', category: 'Diseño UX/UI' },
  { name: 'Adobe XD', category: 'Diseño UX/UI' },
  { name: 'Sketch', category: 'Diseño UX/UI' },
  { name: 'Adobe Photoshop', category: 'Diseño UX/UI' },
  { name: 'Adobe Illustrator', category: 'Diseño UX/UI' },
  { name: 'InVision', category: 'Diseño UX/UI' },
  { name: 'Zeplin', category: 'Diseño UX/UI' },
  { name: 'UX Research', category: 'Diseño UX/UI' },
  { name: 'UI Design', category: 'Diseño UX/UI' },
  { name: 'Wireframes', category: 'Diseño UX/UI' },
  { name: 'Prototyping', category: 'Diseño UX/UI' },
  { name: 'Design Systems', category: 'Diseño UX/UI' },
  { name: 'Usability Testing', category: 'Diseño UX/UI' },
  { name: 'Accessibility', category: 'Diseño UX/UI' },
  { name: 'WCAG', category: 'Diseño UX/UI' },
  { name: 'User Research', category: 'Diseño UX/UI' },
  { name: 'Information Architecture', category: 'Diseño UX/UI' },
  { name: 'Interaction Design', category: 'Diseño UX/UI' },
  { name: 'Visual Design', category: 'Diseño UX/UI' },
  { name: 'Design Thinking', category: 'Diseño UX/UI' },
  { name: 'A/B Testing', category: 'Diseño UX/UI' },
  { name: 'Heatmaps', category: 'Diseño UX/UI' },
  { name: 'User Personas', category: 'Diseño UX/UI' },
  { name: 'Customer Journey', category: 'Diseño UX/UI' },
  { name: 'Color Theory', category: 'Diseño UX/UI' },
  { name: 'Typography', category: 'Diseño UX/UI' },

  { name: 'Scrum', category: 'Gestión' },
  { name: 'Kanban', category: 'Gestión' },
  { name: 'Agile', category: 'Gestión' },
  { name: 'Scrum Master', category: 'Gestión' },
  { name: 'Product Owner', category: 'Gestión' },
  { name: 'Jira', category: 'Gestión' },
  { name: 'Trello', category: 'Gestión' },
  { name: 'Asana', category: 'Gestión' },
  { name: 'Monday.com', category: 'Gestión' },
  { name: 'ClickUp', category: 'Gestión' },
  { name: 'Product Management', category: 'Gestión' },
  { name: 'Project Management', category: 'Gestión' },
  { name: 'User Stories', category: 'Gestión' },
  { name: 'Requirements Analysis', category: 'Gestión' },
  { name: 'UML', category: 'Gestión' },
  { name: 'BPMN', category: 'Gestión' },
  { name: 'Stakeholder Management', category: 'Gestión' },
  { name: 'Risk Management', category: 'Gestión' },
  { name: 'Sprint Planning', category: 'Gestión' },
  { name: 'Retrospectives', category: 'Gestión' },
  { name: 'Daily Standup', category: 'Gestión' },
  { name: 'Backlog Grooming', category: 'Gestión' },
  { name: 'Roadmapping', category: 'Gestión' },
  { name: 'OKRs', category: 'Gestión' },
  { name: 'KPIs', category: 'Gestión' },
  { name: 'PMBOK', category: 'Gestión' },
  { name: 'PRINCE2', category: 'Gestión' },
  { name: 'Change Management', category: 'Gestión' },
  { name: 'Documentation', category: 'Gestión' },
  { name: 'Technical Writing', category: 'Gestión' },

  { name: 'Git', category: 'Herramientas' },
  { name: 'GitHub', category: 'Herramientas' },
  { name: 'GitLab', category: 'Herramientas' },
  { name: 'Bitbucket', category: 'Herramientas' },
  { name: 'VS Code', category: 'Herramientas' },
  { name: 'IntelliJ IDEA', category: 'Herramientas' },
  { name: 'WebStorm', category: 'Herramientas' },
  { name: 'PyCharm', category: 'Herramientas' },
  { name: 'Eclipse', category: 'Herramientas' },
  { name: 'NetBeans', category: 'Herramientas' },
  { name: 'Sublime Text', category: 'Herramientas' },
  { name: 'Vim', category: 'Herramientas' },
  { name: 'Neovim', category: 'Herramientas' },
  { name: 'Notepad++', category: 'Herramientas' },
  { name: 'Notion', category: 'Herramientas' },
  { name: 'Slack', category: 'Herramientas' },
  { name: 'Microsoft Teams', category: 'Herramientas' },
  { name: 'Discord', category: 'Herramientas' },
  { name: 'Zoom', category: 'Herramientas' },
  { name: 'Google Meet', category: 'Herramientas' },
  { name: 'Confluence', category: 'Herramientas' },
  { name: 'SharePoint', category: 'Herramientas' },
  { name: 'Obsidian', category: 'Herramientas' },
  { name: 'Markdown', category: 'Herramientas' },
  { name: 'LaTeX', category: 'Herramientas' },
  { name: 'Postman', category: 'Herramientas' },
  { name: 'cURL', category: 'Herramientas' },
  { name: 'Wget', category: 'Herramientas' },
  { name: 'ngrok', category: 'Herramientas' },
  { name: 'FileZilla', category: 'Herramientas' },
  { name: 'PuTTY', category: 'Herramientas' },
  { name: 'OpenSSH', category: 'Herramientas' },
  { name: 'Terminal', category: 'Herramientas' },
  { name: 'iTerm2', category: 'Herramientas' },
  { name: 'Windows Terminal', category: 'Herramientas' },

  { name: 'Algoritmos', category: 'Ingeniería de Software' },
  { name: 'Estructuras de datos', category: 'Ingeniería de Software' },
  { name: 'Patrones de diseño', category: 'Ingeniería de Software' },
  { name: 'Arquitectura de software', category: 'Ingeniería de Software' },
  { name: 'SOLID', category: 'Ingeniería de Software' },
  { name: 'Clean Code', category: 'Ingeniería de Software' },
  { name: 'Clean Architecture', category: 'Ingeniería de Software' },
  { name: 'DDD', category: 'Ingeniería de Software' },
  { name: 'TDD', category: 'Ingeniería de Software' },
  { name: 'Event-Driven Architecture', category: 'Ingeniería de Software' },
  { name: 'CQRS', category: 'Ingeniería de Software' },
  { name: 'Hexagonal Architecture', category: 'Ingeniería de Software' },
  { name: 'MVC', category: 'Ingeniería de Software' },
  { name: 'MVVM', category: 'Ingeniería de Software' },
  { name: 'OOP', category: 'Ingeniería de Software' },
  { name: 'Functional Programming', category: 'Ingeniería de Software' },
  { name: 'Reactive Programming', category: 'Ingeniería de Software' },
  { name: 'Dependency Injection', category: 'Ingeniería de Software' },
  { name: 'Refactoring', category: 'Ingeniería de Software' },
  { name: 'Code Review', category: 'Ingeniería de Software' },
  { name: 'Pair Programming', category: 'Ingeniería de Software' },
  { name: 'System Design', category: 'Ingeniería de Software' },
  { name: 'API Design', category: 'Ingeniería de Software' },
  { name: 'Performance Optimization', category: 'Ingeniería de Software' },
  { name: 'Scalability', category: 'Ingeniería de Software' },
  { name: 'Concurrency', category: 'Ingeniería de Software' },
  { name: 'Multithreading', category: 'Ingeniería de Software' },
  { name: 'Memory Management', category: 'Ingeniería de Software' },
  { name: 'Debugging', category: 'Ingeniería de Software' },
  { name: 'Logging', category: 'Ingeniería de Software' },
  { name: 'Error Handling', category: 'Ingeniería de Software' },
  { name: 'Versioning', category: 'Ingeniería de Software' },

  { name: 'Redes', category: 'Infraestructura' },
  { name: 'TCP/IP', category: 'Infraestructura' },
  { name: 'DNS', category: 'Infraestructura' },
  { name: 'DHCP', category: 'Infraestructura' },
  { name: 'HTTP/HTTPS', category: 'Infraestructura' },
  { name: 'FTP', category: 'Infraestructura' },
  { name: 'SMTP', category: 'Infraestructura' },
  { name: 'SSH', category: 'Infraestructura' },
  { name: 'LAN', category: 'Infraestructura' },
  { name: 'WAN', category: 'Infraestructura' },
  { name: 'VLAN', category: 'Infraestructura' },
  { name: 'Subnetting', category: 'Infraestructura' },
  { name: 'Routing', category: 'Infraestructura' },
  { name: 'Switching', category: 'Infraestructura' },
  { name: 'Cisco', category: 'Infraestructura' },
  { name: 'MikroTik', category: 'Infraestructura' },
  { name: 'Active Directory', category: 'Infraestructura' },
  { name: 'Windows Server', category: 'Infraestructura' },
  { name: 'Group Policy', category: 'Infraestructura' },
  { name: 'IIS', category: 'Infraestructura' },
  { name: 'SysAdmin', category: 'Infraestructura' },
  { name: 'Help Desk', category: 'Infraestructura' },
  { name: 'IT Support', category: 'Infraestructura' },
  { name: 'Ticketing', category: 'Infraestructura' },
  { name: 'Service Desk', category: 'Infraestructura' },
  { name: 'ITIL', category: 'Infraestructura' },
  { name: 'Asset Management', category: 'Infraestructura' },
  { name: 'Patch Management', category: 'Infraestructura' },

  { name: 'Arduino', category: 'Hardware / IoT' },
  { name: 'Raspberry Pi', category: 'Hardware / IoT' },
  { name: 'ESP32', category: 'Hardware / IoT' },
  { name: 'Microcontroladores', category: 'Hardware / IoT' },
  { name: 'Sensores', category: 'Hardware / IoT' },
  { name: 'Actuadores', category: 'Hardware / IoT' },
  { name: 'IoT', category: 'Hardware / IoT' },
  { name: 'MQTT', category: 'Hardware / IoT' },
  { name: 'PLC', category: 'Hardware / IoT' },
  { name: 'SCADA', category: 'Hardware / IoT' },
  { name: 'Embedded Systems', category: 'Hardware / IoT' },
  { name: 'Firmware', category: 'Hardware / IoT' },
  { name: 'Electrónica', category: 'Hardware / IoT' },
  { name: 'Robótica', category: 'Hardware / IoT' },
  { name: 'Domótica', category: 'Hardware / IoT' },
  { name: 'Impresión 3D', category: 'Hardware / IoT' },
  { name: 'Soldadura', category: 'Hardware / IoT' },
  { name: 'Protoboard', category: 'Hardware / IoT' },

  { name: 'Blockchain', category: 'Emergente' },
  { name: 'Web3', category: 'Emergente' },
  { name: 'Smart Contracts', category: 'Emergente' },
  { name: 'NFT', category: 'Emergente' },
  { name: 'DeFi', category: 'Emergente' },
  { name: 'Metaverse', category: 'Emergente' },
  { name: 'AR/VR', category: 'Emergente' },
  { name: 'Unity', category: 'Emergente' },
  { name: 'Unreal Engine', category: 'Emergente' },
  { name: 'Game Development', category: 'Emergente' },
  { name: 'Quantum Computing', category: 'Emergente' },
  { name: 'Edge Computing', category: 'Emergente' },
  { name: '5G', category: 'Emergente' },
  { name: 'RPA', category: 'Emergente' },
  { name: 'ChatGPT', category: 'Emergente' },
  { name: 'LLM', category: 'Emergente' },
  { name: 'Prompt Engineering', category: 'Emergente' },
  { name: 'Generative AI', category: 'Emergente' },
  { name: 'LangChain', category: 'Emergente' },
  { name: 'Hugging Face', category: 'Emergente' },
  { name: 'Stable Diffusion', category: 'Emergente' },
  { name: 'Midjourney', category: 'Emergente' },
  { name: 'OpenAI API', category: 'Emergente' },

  { name: 'Comunicación efectiva', category: 'Habilidades Blandas' },
  { name: 'Trabajo en equipo', category: 'Habilidades Blandas' },
  { name: 'Liderazgo', category: 'Habilidades Blandas' },
  { name: 'Pensamiento crítico', category: 'Habilidades Blandas' },
  { name: 'Resolución de problemas', category: 'Habilidades Blandas' },
  { name: 'Adaptabilidad', category: 'Habilidades Blandas' },
  { name: 'Creatividad', category: 'Habilidades Blandas' },
  { name: 'Gestión del tiempo', category: 'Habilidades Blandas' },
  { name: 'Aprendizaje continuo', category: 'Habilidades Blandas' },
  { name: 'Empatía', category: 'Habilidades Blandas' },
  { name: 'Inteligencia emocional', category: 'Habilidades Blandas' },
  { name: 'Negociación', category: 'Habilidades Blandas' },
  { name: 'Toma de decisiones', category: 'Habilidades Blandas' },
  { name: 'Atención al detalle', category: 'Habilidades Blandas' },
  { name: 'Proactividad', category: 'Habilidades Blandas' },
  { name: 'Organización', category: 'Habilidades Blandas' },
  { name: 'Responsabilidad', category: 'Habilidades Blandas' },
  { name: 'Puntualidad', category: 'Habilidades Blandas' },
  { name: 'Perseverancia', category: 'Habilidades Blandas' },
  { name: 'Ética profesional', category: 'Habilidades Blandas' },
  { name: 'Mentoría', category: 'Habilidades Blandas' },
  { name: 'Networking', category: 'Habilidades Blandas' },
  { name: 'Oratoria', category: 'Habilidades Blandas' },
  { name: 'Escucha activa', category: 'Habilidades Blandas' },
  { name: 'Manejo de conflictos', category: 'Habilidades Blandas' },
  { name: 'Delegación', category: 'Habilidades Blandas' },
  { name: 'Autogestión', category: 'Habilidades Blandas' },
  { name: 'Pensamiento estratégico', category: 'Habilidades Blandas' },
  { name: 'Trabajo bajo presión', category: 'Habilidades Blandas' },
  { name: 'Colaboración', category: 'Habilidades Blandas' },
  { name: 'Servicio al cliente', category: 'Habilidades Blandas' },
  { name: 'Iniciativa', category: 'Habilidades Blandas' },
  { name: 'Disciplina', category: 'Habilidades Blandas' },
  { name: 'Integridad', category: 'Habilidades Blandas' },
  { name: 'Optimismo', category: 'Habilidades Blandas' },
  { name: 'Curiosidad', category: 'Habilidades Blandas' },
  { name: 'Resiliencia', category: 'Habilidades Blandas' },
  { name: 'Innovación', category: 'Habilidades Blandas' },
  { name: 'Facilidad de aprendizaje', category: 'Habilidades Blandas' },
  { name: 'Orientación a resultados', category: 'Habilidades Blandas' },

  { name: 'Inglés', category: 'Idiomas' },
  { name: 'Español', category: 'Idiomas' },
  { name: 'Portugués', category: 'Idiomas' },
  { name: 'Francés', category: 'Idiomas' },
  { name: 'Alemán', category: 'Idiomas' },
  { name: 'Italiano', category: 'Idiomas' },
  { name: 'Mandarín', category: 'Idiomas' },
  { name: 'Japonés', category: 'Idiomas' },

  { name: 'Finanzas', category: 'Negocios' },
  { name: 'Contabilidad', category: 'Negocios' },
  { name: 'Marketing Digital', category: 'Negocios' },
  { name: 'Ventas', category: 'Negocios' },
  { name: 'CRM', category: 'Negocios' },
  { name: 'Salesforce', category: 'Negocios' },
  { name: 'SAP', category: 'Negocios' },
  { name: 'ERP', category: 'Negocios' },
  { name: 'Business Intelligence', category: 'Negocios' },
  { name: 'Lean Startup', category: 'Negocios' },
  { name: 'Business Analysis', category: 'Negocios' },
  { name: 'Process Improvement', category: 'Negocios' },
  { name: 'Six Sigma', category: 'Negocios' },
  { name: 'Lean Manufacturing', category: 'Negocios' },
  { name: 'Supply Chain', category: 'Negocios' },
  { name: 'Logística', category: 'Negocios' },
  { name: 'Recursos Humanos', category: 'Negocios' },
  { name: 'Selección de personal', category: 'Negocios' },
  { name: 'Capacitación', category: 'Negocios' },
  { name: 'Onboarding', category: 'Negocios' },
  { name: 'Compras', category: 'Negocios' },
  { name: 'Inventarios', category: 'Negocios' },
  { name: 'E-commerce', category: 'Negocios' },
  { name: 'WordPress', category: 'Negocios' },
  { name: 'Shopify', category: 'Negocios' },
  { name: 'WooCommerce', category: 'Negocios' },
  { name: 'Magento', category: 'Negocios' },
  { name: 'SEO', category: 'Negocios' },
  { name: 'SEM', category: 'Negocios' },
  { name: 'Google Analytics', category: 'Negocios' },
  { name: 'Google Ads', category: 'Negocios' },
  { name: 'Facebook Ads', category: 'Negocios' },
  { name: 'Email Marketing', category: 'Negocios' },
  { name: 'Content Marketing', category: 'Negocios' },
  { name: 'Copywriting', category: 'Negocios' },
  { name: 'Social Media', category: 'Negocios' },
  { name: 'Community Management', category: 'Negocios' },
  { name: 'Branding', category: 'Negocios' },
  { name: 'Growth Hacking', category: 'Negocios' },
  { name: 'B2B', category: 'Negocios' },
  { name: 'B2C', category: 'Negocios' },
  { name: 'SaaS', category: 'Negocios' },

  { name: 'Office 365', category: 'Ofimática' },
  { name: 'Microsoft Word', category: 'Ofimática' },
  { name: 'Microsoft Excel', category: 'Ofimática' },
  { name: 'Microsoft PowerPoint', category: 'Ofimática' },
  { name: 'Microsoft Outlook', category: 'Ofimática' },
  { name: 'Google Docs', category: 'Ofimática' },
  { name: 'Google Slides', category: 'Ofimática' },
  { name: 'LibreOffice', category: 'Ofimática' },
  { name: 'ZOOM', category: 'Ofimática' },
  { name: 'Canva', category: 'Ofimática' },
];

export function filterCatalog(query: string, limit = 15): SkillCatalogEntry[] {
  if (!query || query.length < 1) return [];
  const q = query.toLowerCase().trim();
  return SKILL_CATALOG.filter((s) => s.name.toLowerCase().includes(q)).slice(0, limit);
}

export interface SkillCatalogGroup {
  category: string;
  entries: SkillCatalogEntry[];
}

/**
 * Catálogo completo agrupado por categoría, opcionalmente filtrado por nombre.
 * A diferencia de filterCatalog (autocompletado de un campo de texto, limitado
 * a 15 resultados sin categoría), esta función es para el selector de
 * habilidades por catálogo — sin límite, agrupada, pensada para explorar.
 */
export function groupCatalogByCategory(query = ''): SkillCatalogGroup[] {
  const q = query.toLowerCase().trim();
  const byCategory = new Map<string, SkillCatalogEntry[]>();

  for (const entry of SKILL_CATALOG) {
    if (q && !entry.name.toLowerCase().includes(q)) continue;
    if (!byCategory.has(entry.category)) byCategory.set(entry.category, []);
    byCategory.get(entry.category)!.push(entry);
  }

  return Array.from(byCategory.entries())
    .map(([category, entries]) => ({ category, entries }))
    .sort((a, b) => a.category.localeCompare(b.category, 'es'));
}
